### ISSUE TITLE
Tuning/Win Conditions

### ISSUE THREAD

**Issue by mongalong247** [Janne252/coh2-replay-discord-bot#1]
Could the bot be made to show what (if any) tuning pack and/or win conditions were used in the match?

**Comment by Janne252** [comment]
I'll see if https://github.com/ryantaylor/vault supports parsing game setup options.

**Comment by Janne252** [comment]
It appears Vault does not parse game settings.
I've opened an issue: https://github.com/ryantaylor/vault/issues/3
